Get user info/get values from fields
edgardovbak/profil_module pull request #1
Opened 2018-04-09 10:38 UTC by edgardovbak

Hi

Changes 
- Convert to typescript
- jwt authantication
- get user info

2018-04-09 13:15 UTC, gallayl commented on package.json
> +    "sn-client-js": "^3.0.3",
I think sn-client-js should be removed, use the scoped packages

2018-04-09 18:42 UTC, gallayl commented on src/components/EditProfil.tsx
> +							<input id="userName" type="text" ref={(input) => { this.FullName = input as any; }} placeholder="User name" defaultValue={this.props.user.FullName} />
You can use HTMLInputElement type for better intellisense support in such cases

2018-04-09 18:48 UTC, gallayl requested changes

2018-04-09 18:48 UTC, gallayl commented on src/App.tsx
>  const DATA = require('./config.json');
Environment based URLs can be used in long term with React + Webpack with a fallback to the development URL. An example: https://github.com/SenseNet/sn-dms-demo/blob/master/src/index.tsx#L28 and

2018-04-10 08:08 UTC, edgardovbak reviewed
- remove sn-client-js from package.json
- use htmlInputElement type in editprofile
- change repoUrl in App

2018-04-10 13:17 UTC, merged